"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Cornelius Toole"
email = "197863+corntoole@users.noreply.github.com"

[signing]
behavior = "drop"
backend = "ssh"
## You can set `key` to anything accepted by `gpg -u`
## If not set then defaults to the key associated with `user.email`
#key = "77ACE5D7"
key = "~/.ssh/id_ed25519.pub"

[ui]
revsets-use-glob-by-default = true

[git]
sign-on-push = true
write-change-id-header = true

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'

'user(x)' = 'author(x) | committer(x)'
'mine()' = 'user(exact:"197863+corntoole@users.noreply.github.com") | user(exact:"ctoole@zenoss.com") | user(exact:"cornelius.toole@virtana.com")'

# Private and WIP commits that should never be pushed anywhere. Often part of
# work-in-progress merge stacks.
'wip()' = 'description(glob:"wip:*")'
'private()' = 'description(glob:"private:*")'
'blocklist()' = 'wip() | private()'

# stack(x, n) is the set of mutable commits reachable from 'x', with 'n'
# parents. 'n' is often useful to customize the display and return set for
# certain operations. 'x' can be used to target the set of 'roots' to traverse,
# e.g. @ is the current stack.
'stack()' = 'stack(@)'
'stack(x)' = 'stack(x, 2)'
'stack(x, n)' = 'ancestors(reachable(x, mutable()), n)'

# The current set of "open" works. It is defined as: all stacks that are
# reachable from my working copy, or any other commit I wrote.
# n = 1, meaning that nothing from `trunk()` is included, so all resulting
# commits are mutable by definition.
'open()' = 'stack(mine() | @, 1)'

# the set of 'ready()' commits. defined as the set of open commits, but nothing
# that is blacklisted or any of their children.
#
# often used with gerrit, which you can use to submit whole stacks at once:
#
# - jj gerrit send -r 'ready()' --dry-run
'ready()' = 'open() ~ descendants(blocklist())'
# megamerge-related aliases
# Returns the closest merge commit to `to`
"closest_merge(to)" = "heads(::to & merges())"

[aliases]
# via andre.arko.net's JJCon talk, Stupid JJ Tricks
init = ["util", "exec", "--", "bash", "-c", """
jj git init --colocate
# only track origin branches, not upstream or others
jj bookmark track 'glob:*@origin'
"""]

tug = ["util", "exec", "--", "sh", "-c", """
if [ "x$1" = "x" ]; then
  jj bookmark move --from "closest_bookmark(@)" --to "closest_pushable(@)"
else
  jj bookmark move --to "closest_pushable(@)" "$@"
fi
""", ""]

# via @thoughtpolice
# Get all open stacks of work
open = ["log", "-r", "open()"]

# Retrunk revisions. Typically as `jj retrunk -s ...` -- notably can be used
# with open:
# - jj retrunk -s 'roots(open())'
retrunk = ["rebase", "-d", "trunk()"]

# Retrunk the current stack of work.
reheat = ["rebase", "-d", "trunk()", "-s", "roots(trunk()..stack(@))"]

# via andre.arko.net
pr = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  """
gh pr create --head $(jj log -r 'closest_bookmark(@)' -T 'bookmarks' --no-graph | cut -d ' ' -f 1)
""",
]

pull = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  """
closest="$(jj log -r 'closest_bookmark(@)' -n 1 -T 'bookmarks' --no-graph | cut -d ' ' -f 1)"
closest="${closest%\\*}"
jj git fetch
jj log -n 1 -r "${closest}" 2>&1 > /dev/null && jj rebase -d "${closest}" || jj rebase -d 'trunk()'
jj log -r 'stack()'
""",
]

push = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  """
tuggable="$(jj log -r 'closest_bookmark(@)..closest_pushable(@)' -T '"n"' --no-graph)"
[[ -n "$tuggable" ]] && jj tug
pushable="$(jj log -r 'remote_bookmarks(remote=origin)..@' -T 'bookmarks' --no-graph)"
[[ -n "$pushable" ]] && jj git push || echo "Nothing to push."
closest="$(jj log -r 'closest_bookmark(@)' -n 1 -T 'bookmarks' --no-graph | cut -d ' ' -f 1)"
closest="${closest%\\*}"
tracked="$(jj bookmark list -r ${closest} -t -T 'if(remote == "origin", name)')"
[[ "$tracked" == "$closest" ]] || jj bookmark track "${closest}@origin"
""",
]

# megamerge-related aliases
# Inserts the given revset as a new branch under the megamerge.
stack = [
  "rebase",
  "--after",
  "trunk()",
  "--before",
  "closest_merge(@)",
  "--revision",
]
# Stages multiple revsets under the  megamerge.
stage = ["stack", "closest_merge(@)+:: ~ empty()"]
# Rebases writable stacks onto trunk in order to keep the branches under the megamerge up to date.
restack = [
  "rebase",
  "--onto",
  "trunk()",
  "--source",
  "roots(trunk()..) & mutable()",
  "--simplify-parents",
]
