{ config, pkgs, modulesPath, ... }:

{
  imports = [
    # Include the default lxd configuration.
    "${modulesPath}/virtualisation/lxc-container.nix"
    # Include the container-specific autogenerated configuration.
    ./incus.nix
    # Include the OrbStack-specific configuration.
    ./orbstack.nix
  ];

  # Enable modern Nix features (Flakes and new CLI tools)
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  virtualisation = {
    containers.enable = true;
    docker = {
      enable = true;
      enableOnBoot = true;
    };
  };

  # System-wide packages
  environment.systemPackages = with pkgs; [
    bat
    curl
    docker-compose
    eza
    fzf
    git
    (google-cloud-sdk.withExtraComponents [
      google-cloud-sdk.components.gke-gcloud-auth-plugin
      google-cloud-sdk.components.kubectl
    ])
    gnumake
    htop
    jujutsu
    neovim
    nixd
    ripgrep
    starship
    tmux
    tree
    wget
    zoxide
  ];

  # Inside your /etc/nixos/configuration.nix
  environment.enableAllTerminfo = true;


  # Enable nix-ld (Fixes VS Code Remote SSH and external binaries)
  programs.nix-ld.enable = true;

  users.users.corneliustoole = {
    uid = 503;
    extraGroups = [ "networkmanager" "wheel" "orbstack" "audio" "docker" ];

    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/corneliustoole";
    homeMode = "700";
    useDefaultShell = true;

    # Allocates 65,536 IDs starting at 100,000 for rootless containers
    subUidRanges = [{ startUid = 100000; count = 65536; }];
    subGidRanges = [{ startGid = 100000; count = 65536; }];
  };

  security.sudo.wheelNeedsPassword = false;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "America/Chicago";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };

  # Automatic optimization and storage cleanup
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 7d";
  };
  nix.settings.auto-optimise-store = true;

  system.stateVersion = "25.11";
}
