local o = vim.opt
vim.g.mapleader = ' '
o.expandtab = true
o.shiftwidth = 2
o.number = true
o.relativenumber = true
o.smartindent = true
o.clipboard = "unnamedplus"
o.scrolloff = 16
o.undofile = true
